name: CD
on:
  push:
    branches:
      - main

env:
  SERVICE_NAME: default-service
  IMAGE_NAME: default-service-fastapi
  PROJECT: originations
  GCP_PROJECT_ID: firebase-svelte-381023

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Build docker image
        run: docker build --platform linux/amd64 -t $IMAGE_NAME:latest .

      - name: Tag docker image
        run: docker tag $IMAGE_NAME europe-west3-docker.pkg.dev/$GCP_PROJECT_ID/$PROJECT/$IMAGE_NAME

      - name: Login
        run: gcloud auth login

      - name: Configure gcloud auth for docker
        run: |
          gcloud auth configure-docker -q

      - name: Push docker image to GCR
        run: docker push europe-west3-docker.pkg.dev/$GCP_PROJECT_ID/$PROJECT/$IMAGE_NAME

      - name: Deploy new docker image to prod
        run: |
          gcloud run deploy $SERVICE_NAME --image europe-west3-docker.pkg.dev/$GCP_PROJECT_ID/$PROJECT/$IMAGE_NAME --region europe-west3 --port 80 --memory 4Gi
